### ISSUE TITLE
Break in wrong place - raises Access Denied, not Compile Error.

### ISSUE THREAD

**Issue by 3FLLC** [nielsAD/lape#114]
Run the following code, I get:
Compilation error: "Access violation"

    procedure CallMethod;
    Begin
       Writeln('Hey');
       Break;
    end;
    
    Begin
       CallMethod;
    End.

It has taken me forever to figure out how to reproduce this. I was busy redesigning some case statements into procedures.

**Comment by nielsAD** [comment]
Thanks!

**Comment by 3FLLC** [comment]
@nielsAD Fixed?

**Comment by nielsAD** [comment]
Yes, see the referenced commit above.
