### ISSUE TITLE
Break out of place raises a compilation error.

### ISSUE THREAD

**Issue by 3FLLC** [nielsAD/lape#139]
`Begin
   Break;
End`

I am unable to trace the code on my Mac to see where this trips up ... but, it happens with even a simple piece of code as above. If a Break is out of place, "Access Violation" without any details of where ~ and on a BIG project this is a PITA to find.

Can anyone supply a patch to report a valid error - with line/column of where this should be fixed in the script source?

**Comment by ollydev** [comment]
You've already reported this, and it was fixed.
https://github.com/nielsAD/lape/issues/114
https://github.com/nielsAD/lape/commit/1b955e5864cf2d3503ec6b2cfd383830837f0dc4

**Comment by 3FLLC** [comment]
Yes. Sorry, did not see the fix... applied. Thank you for pointing it out.
