### ISSUE TITLE
Lape debug mode

### ISSUE THREAD

**Issue by Vizit0r** [nielsAD/lape#153]
As i see:
No debug mode implemented for lape.
ATM i found only way to take values of global vars, and thats all. No params&result values, no methods vars, no step into&over, etc.
Compiler provide all needed info, but with values from interpreter big problems.

If all above is correct, please advise, do you have a plans for this feature in your roadmap?
If i mess something - please advice, where to dig in.

**Comment by ollydev** [comment]
I think the basic idea is to pass StackInfo to the interpreter then use `VarToString(AVar: Pointer): lpString;` on the current VarStack.

**Comment by Vizit0r** [comment]
dive deeper and deeper there.

One more question: when script is running, if its possible to exec script method from Delphi (in same script area, means shared vars etc) ?
I found the way how to exec it in lpffiwrappers.pas, but not sure about same script area, seems like its separated.

**Comment by ollydev** [comment]
It works fine using ffi.
https://i.imgur.com/5D8QK9n.png

So LapeExportWrapper. or Natify in the script and pass the pointers back to FPC.

**Comment by Vizit0r** [comment]
1) ffi was developed and designed for FPC only, not so easy to transfer it to Delphi.
2)i see only Win dlls, nothing for other platforms, 
Without ffi no way?

**Comment by ollydev** [comment]
I think FFI should work on Delphi? There might be some minor compile errors as it's never been compiled using Delphi (I think)
Lape loads FFI from the system on macOS/Linux. So `apt-get install libffi-dev` or `brew install libffi`.

You can call script methods using RunCode by using `InitialJump`:
`RunCode(Compiler.Emitter.Code, Compiler.Emitter.CodeLen, [{var stack}], PCodePos(Compiler['SomeScriptMethod'].Ptr)^);`

But variables, I am not sure on. I've only used above to call just to call the most basic `procedure SomeScriptMethod;` method.

**Comment by Vizit0r** [comment]
will try it later, thanks.

Now i try to find the way to obtain list of vars for current stack area, still nothing. Some vars i can get, but thats not a result.

**Comment by Vizit0r** [comment]
Question with script methods calling solved fast and easy, thanks @ollydev again,

For my purpose enough simple types in params, without retur values.

Now only question with debug left, but i'm stacked again. Have no idea, what to do. Too much of temp vars, all translated to pointers, and no some common origin var to refer on. 
Have some crazy ideas, like make magic methods for every var and param, and call them outside -but its really crazy.


example on script method calling:

script:
`var bbb : Integer;
procedure SomeScriptMethod(Xorig, Yorig : Word; Dir : Byte; X, Y : Word);
begin
 AddToSystemJournal('Xorig='+IntToStr(Xorig));
 AddToSystemJournal('Yorig='+IntToStr(Yorig));
 AddToSystemJournal('Dir='+IntToStr(Dir));
 AddToSystemJournal('X='+IntToStr(X));
 AddToSystemJournal('Y='+IntToStr(Y));
  bbb := 100;
end;
Begin
bbb := 800;//ttest(199);
AddToSystemJournal(IntToStr(bbb));
Wait(1);
AddToSystemJournal(IntToStr(bbb));
End.
`
and Delphi:
`    Compiler : TLapeCompiler;
    VarStack: lptypes.TByteArray;
    Xorig, Yorig : Word; Dir : Byte; X, Y : Word;
    TotalParamsLen : Integer;
begin
  Compiler := TBaseLapeScriptThread(CurrScriptThread).Compiler;
  Xorig := 500; Yorig := 600; Dir := 91; X := 700; Y := 800;
  TotalParamsLen := SizeOf(Xorig) + SizeOf(Yorig) + SizeOf(Dir) +
                    SizeOf(X) + SizeOf(Y);
  SetLength(VarStack, TotalParamsLen);
  k := 0;
  Move(Xorig,VarStack[0],SizeOf(Xorig));
  Inc(k,SizeOf(Xorig));
  Move(Yorig,VarStack[k],SizeOf(Yorig));
  Inc(k,SizeOf(Yorig));
  Move(Dir,VarStack[k],SizeOf(Dir));
  Inc(k,SizeOf(Dir));
  Move(X,VarStack[k],SizeOf(X));
  Inc(k,SizeOf(X));
  Move(Y,VarStack[k],SizeOf(Y));

  RunCode(Compiler.Emitter.Code, Compiler.Emitter.CodeLen, VarStack, PCodePos(Compiler['SomeScriptMethod'].Ptr)^);`

returns `22:01:02:304 : Compiling
22:01:02:358 : Compiled succesfully
22:01:02:358 : 800
22:01:02:358 : Xorig=500
22:01:02:358 : Yorig=600
22:01:02:358 : Dir=91
22:01:02:358 : X=700
22:01:02:358 : Y=800
22:01:02:358 : 100
22:01:02:358 : Succesfully executed
22:01:02:358 : Script Test.sc stopped successfuly`

**Comment by ollydev** [comment]
Hmmm? You just want a easier way to generate the var stack? If only needing base types, this comes to mind.

```pascal
function getVar(BaseType, Value: String): TByteArray;
var
  Variable: TLapeGlobalVar; // will need to manage (free) me
begin
  Variable := Compiler.getBaseType(BaseType).NewGlobalVarStr(Value);
  SetLength(Result, Variable.Size);
  Move(PPointer(Variable.Ptr)^, Result[0], Variable.Size);
end; 

RunCode(Compiler.Emitter.Code, Compiler.Emitter.CodeLen, getVar('AnsiString', 'Hello world') + getVar('Int32', '123456'), PCodePos(Compiler['SomeScriptMethod'].Ptr)^);
```

Script:
```pascal
procedure SomeScriptMethod(Str: AnsiString; I: Int32);
begin
  Writeln('Str: ', Str);
  WriteLn('I: ', I);
end;

begin
end;
```

Output: 
```
Str: Hello world
I: 123456
```

You could also verify you've passed the correct varstack by comparing what you generate to ` TLapeType_Method(Compiler['SomeScriptMethod'].VarType).Params; ` and so on...

Going to bed now, Good luck!

**Comment by Vizit0r** [comment]
its just for test purposes, in real code i will obtain VariantArray and transfer it to code.
And yes, i want to do some method like this, but generic.

P.S. Constant param size also for tests only, first i check it by TLapeType_Method(TBaseLapeScriptThread(CurrScriptThread).Compiler['SomeScriptMethod'].VarType).Params.

**Comment by ollydev** [comment]
If you didn't know the script can accept a variant array very easily as it's just a pointer. Just pass the pointer to a variant array and lape (should) handle it fine. :)

```pascal
var test: TVariantArray; 
begin
SetLength(test, 3);
test[0] := 123;
test[1] := 'hello';
test[2] := 123.4;

SetLength(bytes, SizeOf(Pointer));
Move(Pointer(Test), bytes[0], SizeOf(Pointer));

RunCode(Compiler.Emitter.Code, Compiler.Emitter.CodeLen, bytes, PCodePos(Compiler['SomeScriptMethod'].Ptr)^); 
```
Might be easier?

Or this is what you want.
(No error checking)

```pascal
  function AddVar(VarType: TLapeType; Value: String): TByteArray;
  var
    Variable: TLapeGlobalVar; // will need to manage (free) me
  begin
    Variable := VarType.NewGlobalVarStr(Value);
    SetLength(Result, Variable.Size);
    Move(PPointer(Variable.Ptr)^, Result[0], Variable.Size);
  end;

  procedure Call(Method: String; Params: array of Variant);
  var
    m: TLapeType_Method;
    i: Int32;
    Vars: TByteArray;
  begin
    m := TLapeType_Method(Compiler[Method].VarType);
    for i := 0 to m.Params.Count - 1 do
      Vars += AddVar(m.Params[i].VarType, VarToStr(Params[i]));

    RunCode(Compiler.Emitter.Code, Compiler.Emitter.CodeLen, Vars, PCodePos(Compiler[Method].Ptr)^);
  end;
  ```

Okay, Actually bed time...

**Comment by Vizit0r** [comment]
> Might be easier?

seems like not. Thank you.

**Comment by Vizit0r** [comment]
@ollydev 
Please advice, class improving (like on your screenshot) made using ffi ?

**Comment by Vizit0r** [comment]
Does exists some way to add method, who will look like a var in script?
I want to import class properties. Now i have
    Compiler.addGlobalFunc('function DiscordMessenger.Token: string;overload;', @_GetMesNameWrap);
    Compiler.addGlobalMethod('procedure DiscordMessenger.Token(Value : String);overload;', @_SetMesNameWrap, nil);
in script
  DiscordMessenger.Token('124zzzz');
  AddToSystemJournal(DiscordMessenger.Token);
works fine.

But i need to do it in classic way,
DiscordMessenger.Token := '124zzzz';
otherwise compatibility with old user scripts will be broken, that is not what i want.

**Comment by Vizit0r** [comment]
Does exists some way to add method, who will look like a var in script?
I want to import class properties. Now i have
    Compiler.addGlobalFunc('function DiscordMessenger.Token: string;overload;', @_GetMesNameWrap);
    Compiler.addGlobalMethod('procedure DiscordMessenger.Token(Value : String);overload;', @_SetMesNameWrap, nil);
in script
  DiscordMessenger.Token('124zzzz');
  AddToSystemJournal(DiscordMessenger.Token);
works fine.

But i need to do it in classic way,
DiscordMessenger.Token := '124zzzz';
otherwise compatibility with old user scripts will be broken, that is not what i want.

**Comment by ollydev** [comment]
Properties have not been implemented into Lape.

**Comment by Vizit0r** [comment]
```
 TDropDelay = record
  private
    fData : Cardinal;
  public
    class operator Implicit(const Value: Cardinal): TDropDelay; overload;
    class operator Implicit(const Value: TDropDelay): Cardinal; overload;
  end;
```

something in this manner also cant be done?

**Comment by Vizit0r** [comment]
@ollydev     Implemented, lcoAutoProperties in Compiler Options solve this question.

So, now left only the question about local vars&params value obtaining, ang get call stack as string list.  Will explore it more.

BTW, i'm add to parser support of unit (uses XXX;) for compatibility with old PS scripts, not sure anyone else need this.

**Comment by Vizit0r** [comment]
one more question regardings compilation to bytecode.
After successfull compilation i save bytecode to file. 
Next time i read it, pass to Interpreter, it runs few first instruction, than dying on lpePointer_ASGN_Pointer, ptr = nil

LapeCompiler.Options := LapeCompiler.Options - [lcoAlwaysInitialize];

It there some way to run it without sources compilation?

**Comment by ollydev** [comment]
No work on bytecode loading/saving has ever been done.
First thought you will have to relink all imported methods, global variables and generate all constant values. Likely other stuff too.

I don't think you've done since `lcoAlwaysInitialize` just defaults the variable with zeros. Does not do any memory allocation, so has nothing to with a nil pointer.

**Comment by Vizit0r** [comment]
i try with lcoAlwaysInitialize, and without. no matter.
In PS for correct running compiled scripts for PSExec you have special methods for settings pointer addresses for imported vars.
For Lape, ofc if no this setup  done before running - all imported global vars pointing to dev>null.
But atm i have no idea where and how this have to be done.

**Comment by ollydev** [comment]
You could save PS compiled code? Never knew that. We used to use that in Simba.
And yeah I said there has been no work done on loading/saving bytecode, nor have I attempted so I don't really know "where and how this has to be done"

**Comment by Vizit0r** [comment]
If you need, i can send you a code.


well understood.
Thats not a critical option, will pack and ecrypt whole file (with inserted includes) and compile it in silent mode every time.
Bad way, but way :)

Still try to understand tree logic, to find a ptrs of local vars&params, but still failed...

P.S. Take a part with callstack getting by EnterMethod&LeaveMethod from Simba, its really good, thanks.

**Comment by JohnPeel** [comment]
Not sure anymore how Lape does it, but to support bytecode saving/loading it would need to compile the script to an intermediate bytecode and have an interpreter for that bytecode.

That bytecode could be saved with a symbol table for external functions, then when loading you replace the table with the external implementations.

I doubt Lape supports this with it's current implementation.

**Comment by Vizit0r** [comment]
yes, it doesnt support.

BTW, quesion with local vars\params values solved (based on priciples of Enter\Leave Method by olly).


P.S. calling script methods as called before - works, but cause memory corruption (string, which in use, disposed. Cant locate the exact place.

Now try to use ffi...

**Comment by Vizit0r** [comment]
@ollydev i need help. my skills not enough to understood the reason of bug, lost 6 days, but

 still not found root reason of error.

I have a small script, cuted from huge script(more than 15k lines), to reproduce error.
Error coming in line 489 (preparation function params),  but real reason is bit earlier.
In my own log i write execution of all opcodes(with addresses) + deep logging in method lpeUString_ASGN_UString + detection of writing value $2106C, its "constant" (until script changing).

So, in my log most interesting lines 9090 (error detected), and 9067-9068 (setting non string-value).
Pointer to non-string value assigned, and when on error line it try to check string by ptr and its refcount - Access Violation raised.

For both operations StackPos = 48, its seems like error, but i'm not sure.

The biggest problem, that 100%  error repeating available in my program only, seems like due to specific Lape imported methods and types. I try to execute script in Simba - all is ok.
Look it please, if you have free time...


Attached 4 files: 1) script with bug 2)disassembled log 3) my additional log 4) small log with AV info.

[LapeOps_612.log](https://github.com/nielsAD/lape/files/6160882/LapeOps_612.log)
[DISASM.log](https://github.com/nielsAD/lape/files/6160897/DISASM.log)
[Exec_Error.log](https://github.com/nielsAD/lape/files/6160904/Exec_Error.log)
[script_BUGGG.txt](https://github.com/nielsAD/lape/files/6160886/script_BUGGG.txt)

**Comment by ollydev** [comment]
@Vizit0r There is some kind low level bug related to records (as far as I can tell)

Here is a bad bug report I made a little bit ago. https://github.com/nielsAD/lape/issues/147

When I constref your script so no record copies are made, it succesfully executes.
`function GetFatigueThreshold(constref city:TCity; constref Info:TGumpInfo2 ): Integer;`

Today I found another bug with record compare only on 32 bit, in this example at least.

https://i.imgur.com/bkcYm4S.png

I will try to fix these bugs in the coming days with niels.

**Comment by Vizit0r** [comment]
good that you already knows about this deep bug, hope you will fix it.

BTW, the subject is already solved, file with code attached. Not sure it covers ALL types, but for on my tests its works fine. Not test it for Variants at all.

Maybe will be useful for someone. 

[lape local methods debug.txt](https://github.com/nielsAD/lape/files/6193476/lape.local.methods.debug.txt)
