### ISSUE TITLE
IntToHex, Default Digits to 1.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nielsAD/lape#17]
```
Will allow people to use IntToHex with only one parameter.

I tested and seems to work fine.
```

Original issue reported on code.google.com by `Dgby...@gmail.com` on 3 Aug 2012 at 1:00

Attachments:
- [test.diff](https://storage.googleapis.com/google-code-attachments/la-pe/issue-17/comment-0/test.diff)

**Comment by 3FLLC** [comment]
May I suggest, default is 2. As most people would expect standard notation of 0F for 15 not F. (just reviewing all issues).
