### ISSUE TITLE
Lape usage on Delphi 

### ISSUE THREAD

**Issue by Vizit0r** [nielsAD/lape#170]
Seems like last year nobody test it (or even try to compile) on Delphi, many new FP-only things found.

So, i've made changes for Delphi (including Linux & MacOs) in my repo (all changes described)
https://github.com/Vizit0r/lape/commit/7125790e3b15a8f99466387823039fbcd5a011a7

dont want to pull it here yet due to some amount of failed tests (especially on Linux-MacOs) - read commit description.
From my side, i fix all what i can, remaining failed tests need real understanding of internal mechanics, i'm not good in that.

@ollydev , can you please install Delphi, and find the reason of bugs?

in Lazarus all tests passed successfully. 

Linux tests results attached for reference - [Linux tests.txt](https://github.com/nielsAD/lape/files/7317237/Linux.tests.txt)

P.S. In FFI all is much worse, last time i make it work partially, but not fully. Later on will try again from zero.

**Comment by ollydev** [comment]
Lape has never really been used much on Delphi - just compile fixes once in a while.
The Linux tests are quite worrying. I suspect this was because Delphi was Windows only when Lape was mainly being developed in early 2010s.

FFI is another story. FPC and Delphi seem to have a lot of differences at what they do with parameters with calling conventions.

I will soon download Delphi on Linux and have a look though.

**Comment by Vizit0r** [comment]
Ok, call me if any question with Delphi, linux\macos preparation, running, etc.

**Comment by ollydev** [comment]
Updated https://github.com/ollydev/lape/tree/delphi-fixes

Every normal test passes on macOS. Can't test linux but should be the same.
Will tidy up and merge here soon.

![](http://ollydev.mooo.com/uploads/VirtualBoxVM_YTyT0oCsaR.png)

**Comment by ollydev** [comment]
merged #172

For FFI, fpc now has it's own FFI stuff. Lape should take note from it as some of lape FFI was guessed and hacked. Where this should have the answers.
https://gitlab.com/freepascal.org/fpc/source/-/blob/main/packages/libffi/src/ffi.manager.pp
