### ISSUE TITLE
Shameless plug

### ISSUE THREAD

**Issue by gcarreno** [nielsAD/lape#181]
Hi there,

I'm completely aware that Olly (@ollydev) is one of the contributors to this project and you're using his `setup-lazarus` action.

I too have developed one that is configured based on Lazarus versions, not on the file URLs present on sourceforge.
It does, nonetheless, in the background, use the same files you now have to input by hand.

With my version you don't have to remember or even copy paste the actual files. You just have to mention a version.
Mine also has the version name `stable` that I try really hard to maintain up to date with the current stable version.
With this, you can leave the Lazarus version alone and just update the action's version and you get an instant new stable version to test.
At the time of writing this, `stable:=2.2.2` and I just updated it yesterday, if I'm not mistaken.

My action also has a semi-complete support for `packages.lazarus-ide.org` or the Online Package Manager.
I say semi-complete because I've been lazy to implement drilling down and adding all dependencies, and dealing with a Meta Package that has multiple packages.
Yes, I know, semi-complete is an understatement when I mention what's missing, but hey `¯\_(ツ)_/¯`

There's a companion project that I maintain with a very basic example on ho to use it:
https://github.com/gcarreno/lazarus-with-github-actions

If you feel that this is too intrusive and I should peddle my wares somewhere else, please feel free to give me the boot 😃

Cheers,
Gus

**Comment by nielsAD** [comment]
Hi @gcarreno, looks like a nice project!

Currently, I don't see the benefit in switching, as it looks like you are still manually listing all versions and corresponding URLs in the source code, so we would depend on the action being kept up to date. For now, I prefer to keep using the action developed by one of our core contributors, but I'll keep an eye on your project!

**Comment by gcarreno** [comment]
Hey Niels (@nielsAD),

> Hi @gcarreno, looks like a nice project!

Many thanks for the kind words.

> Currently, I don't see the benefit in switching ...

That's perfectly OK. Like I said, it was a shameless plug and you were in your right to send me off 😉

> as it looks like you are still manually listing all versions and corresponding URLs in the source code, so we would depend on the action being kept up to date.

I cannot disagree with you here 😃

I think we cater to different audiences here.
While you cater for the type of person that needs/wants absolute control, I'm aiming at the ones that do not mind something that just works.

Your way you can have absolute control and you just automate ~50% of the whole.

My way you just input a set of numbers and the automation does the rest, so around 95%.
It also limits you to a specific set of numbers and doesn't let you error outside of it.

So yeah, different audiences.

> For now, I prefer to keep using the action developed by one of our core contributors, but I'll keep an eye on your project!

That's all a person like me can expect, so many thanks for the kind words.

One of the things that really caught my eye is Olly's `fpcup` alternative where we can get the cross compiling.

I've been slowly simmering in the back burner a way to do the installation of cross-compiling with this exact method for a while.
I've also had the same idea of having a separate action for it.
But now I'm thinking that if I throw in a switch (something like cross: boolean), maybe I can get away of putting everything under the same action.

But before I enter those choppy waters, first I need to finish the full OPM integration 😃

Cheers,
Gus
