### ISSUE TITLE
Run script function\procedure with parms and result from native pascal

### ISSUE THREAD

**Issue by zamtmn** [nielsAD/lape#196]
Do we have the opportunity to run a separate function in script without running the script as a whole? naturally, from native pascal code,  send the parameters to her and taking the result? Please show an example of doing this if possible

**Comment by Vizit0r** [comment]
long time ago, when i try to achive lape to working state, i use construction like

(no code format due to poor connection, page js's cant be loaded properly )

  Result := LapeCompiler.Compile();
....
  if Result then
  begin
    PPCode := LapeCompiler.Emitter.Code;
    CodeLen := LapeCompiler.Emitter.CodeLen;
  end;

function TBaseLapeScriptThread.execfunction(EventType : TPacketEvent; EventMethod : Pointer; Params : array of Variant) : Variant;
var ClassAsInt : NativeInt;

Text, SenderName : String; SenderID:Cardinal;
begin
  if not Assigned(LapeCompiler) then
    Exit;
  //because call coming from TCharacter thread!
  CurrScriptThread := Self;
  case EventType of
    evItemInfo : TEvItemInfoCallBack(EventMethod)(Params[0]);
    evItemDeleted : TEvItemDeletedCallBack(EventMethod)(Params[0]);
    evSpeech :
    begin
      Text := Params[0];
      SenderName := Params[1];
      SenderID := Params[2];
      TEvSpeechCallBack(EventMethod)(Text, SenderName, SenderID);
      //TEvSpeechCallBack(EventMethod)(Params[0],Params[1],Params[2]);
    end;
    evDrawGamePlayer : TEvDrawGamePlayerCallBack(EventMethod)(Params[0]);
    evMoveRejection : TEvMoveRejectionCallBack(EventMethod)(Params[0],Params[1],Params[2],Params[3],Params[4]);
    evDrawContainer : TEvDrawContainerCallBack(EventMethod)(Params[0], Params[1]);
    evAddItemToContainer :
    begin
//      Script_AddToSystemJournal( 'Delphi evAddItemToContainer[ itemID:$' + IntToHex( Params[0], 8 )  + ', containerID:$' + IntToHex( Params[1], 8 ) + ' ]' );
      TEvAddItemToContainerCallBack(EventMethod)(Params[0],Params[1]);
    end;
    evAddMultipleItemsInCont : TEvAddMultipleItemsInContCallBack(EventMethod)(Params[0]);
    evRejectMoveItem : TEvRejectMoveItemCallBack(EventMethod)(Params[0]);
    evUpdateChar : TEvUpdateCharCallBack(EventMethod)(Params[0]);
    evDrawObject  : TEvDrawObjectCallBack(EventMethod)(Params[0]);
    evMenu : TEvMenuCallBack(EventMethod)(Params[0], Params[1]);
    evMapMessage : TEvMapMessageCallBack(EventMethod)(Params[0],Params[1],Params[2]);
    evAllow_RefuseAttack : TEvAllow_RefuseAttackCallBack(EventMethod)(Params[0], Params[1]);
    evClilocSpeech : TEvClilocSpeechCallBack(EventMethod)(Params[0],Params[1],Params[2],Params[3]);
    evClilocSpeechAffix : TEvClilocSpeechAffixCallBack(EventMethod)(Params[0],Params[1],Params[2],Params[3], Params[4]);
    evUnicodeSpeech : TEvUnicodeSpeechCallBack(EventMethod)(Params[0],Params[1],Params[2]);
    evBuff_DebuffSystem : TEvBuff_DebuffSystemCallBack(EventMethod)(Params[0],Params[1],Params[2]);
    evClientSendResync  : TEvClientSendResyncCallBack(EventMethod)();
    evCharAnimation : TEvCharAnimationCallBack(EventMethod)(Params[0],Params[1]);
    evIncomingGump : TEvIncomingGumpCallBack(EventMethod)(Params[0],Params[1],Params[2],Params[3]);
    evTimer1,
    evTimer2 : TEvTimerCallBack(EventMethod)();
    evWindowsMessage : TEvWindowsMessageCallBack(EventMethod)(Params[0]);
    evSound : TEvSoundCallBack(EventMethod)(Params[0],Params[1],Params[2],Params[3]);
    evDeath : TEvDeathCallBack(EventMethod)(Params[0]);
    evQuestArrow : TEvQuestArrowCallBack(EventMethod)(Params[0],Params[1],Params[2]);
    evPartyInvite : TEvPartyInviteCallBack(EventMethod)(Params[0]);
    EvMapPin : TEvMapPinCallBack(EventMethod)(Params[0],Params[1],Params[2],Params[3], Params[4]);
    EvGumpTextEntry : TEvGumpTextEntryCallBack(EventMethod)(Params[0],Params[1],Params[2],Params[3], Params[4]);
    evGraphicalEffect : TEvGraphicalEffectCallBack(EventMethod)(Params[0],Params[1],Params[2],Params[3], Params[4],
                                                      Params[5],Params[6],Params[7],Params[8], Params[9], Params[10]);
    evIRCIncomingText : TEvIRCIncomingTextCallBack(EventMethod)(Params[0]);
    evMessengerEvent :
    begin
      ClassAsInt := NativeInt(Params[0]);
      TEvMessengerEventCallBack(EventMethod)(TObject(ClassAsInt),Params[1],Params[2],Params[3],Params[4],Params[5]);
    end;
    evSetGlobalVar : TEvSetGlobalVarCallBack(EventMethod)(Params[0],Params[1]);
    evUpdateObjStats : TEvUpdateObjStatsCallBack(EventMethod)(Params[0],Params[1],Params[2],Params[3], Params[4], Params[5],Params[6]);
    evGlobalChat : TEvGlobalChatCallBack(EventMethod)(Params[0],Params[1],Params[2]);
  end;

  if not ExecEvMethodError.IsEmpty and ValidObject(CharObj) then
    Script_AddToSystemJournal(ExecEvMethodError);
end;

**Comment by ollydev** [comment]
You can do above, but you have to construct everything yourself.
Using lape's libffi interface is ideal for this.

Some lape code...
```pascal
function test(a, b: Int32): String;
begin
  Result := IntToStr(a) + '-' + IntToStr(b);
end;
```

In FPC after script has been compiled, this will call the above lape function
```pascal
uses
  lpffiwrappers;

type
  TMyTest = function(a, b: Integer): String;
  
WriteLn(TMyTest(LapeExportWrapper(Compiler['test']).Func)(123,456)); 
```

**Comment by zamtmn** [comment]
[Vizit0r](https://github.com/Vizit0r)
Thanks!

[ollydev](https://github.com/ollydev)
There is a way to first make sure that the procedure in the script has exactly such a declaration?

**Comment by ollydev** [comment]
```pascal
      methodType := TLapeType_Method(TLapeGlobalVar(Compiler['Test']).VarType);
      WriteLn(methodType.Params.Count);
      WriteLn(methodType.Params[0].VarType.Name);
      WriteLn(methodType.Res.Name);
```

**Comment by zamtmn** [comment]
Thanks! It's nice to have a quick response!

**Comment by Vizit0r** [comment]
> Using lape's libffi interface is ideal for this.

yes, if you use lape only in windows :)

**Comment by zamtmn** [comment]
doesn't ffi work on linux?

**Comment by ollydev** [comment]
it does work fine on other platforms.

**Comment by Vizit0r** [comment]
> it does work fine on other platforms.

But not all of them, thats why i have to do those strange things with script methods execution :)

**Comment by ollydev** [comment]
Do you have any examples? All current tests pass
![image](https://github.com/nielsAD/lape/assets/3413206/23b89656-3ec2-466d-b2d9-ba1fd877cb9f)

**Comment by Vizit0r** [comment]
> Do you have any examples? All current tests pass

https://github.com/nielsAD/lape/issues/170

**Comment by zamtmn** [comment]
Thanks! This can be closed. If there are problems, I will make a new report

**Comment by jarroddavis68** [comment]
> long time ago, when i try to achive lape to working state, i use construction like
> 
> ```
>   Result := LapeCompiler.Compile();
> ....
>   if Result then
>   begin
>     PPCode := LapeCompiler.Emitter.Code;
>     CodeLen := LapeCompiler.Emitter.CodeLen;
>   end;
> 
> function TBaseLapeScriptThread.execfunction(ProcName : String; Params : array of Variant; IsEvent : Boolean = False) : Variant;
> var ParamVars : TObjectList<TLapeGlobalVar>;
>     m : TLapeType_Method;
>     i : Integer;
>     VarStack2: lptypes.TByteArray;
> 
>   function getVar(BaseType: TLapeType; Value: String) : lptypes.TByteArray;
>   var LapeVar : TLapeGlobalVar;
>   begin
>     LapeVar := BaseType.NewGlobalVarStr(Value);
>     ParamVars.Add(LapeVar);
>     SetLength(Result, LapeVar.Size);
>     Move(PPointer(LapeVar.Ptr)^, Result[0], LapeVar.Size);
>   end;
> 
> begin
>   if not Assigned(LapeCompiler) then
>     Exit;
>   if (not Assigned(LapeCompiler[ProcName])) then
>   begin
>     ExecEvMethodError := 'Error exec method: - Method with name "' + ProcName + '" is not exists!';
>     Exit;
>   end;
>   if not Assigned(LapeCompiler[ProcName].VarType) then
>   begin
>     ExecEvMethodError := 'Error exec method: - Method with name "' + ProcName + '" has incorrect type!';
>     Exit;
>   end;
>   m := TLapeType_Method(LapeCompiler[ProcName].VarType);
> 
>   if Length(Params) < m.Params.Count then
>   begin
>     ExecEvMethodError := Format('Error exec method: Wrong number of parameters found (%d), expected %d',
>                                 [Length(Params), m.Params.Count]);
>     Exit;
>   end;
> 
>   //pushing params & vars to stack
>   ParamVars := TObjectList<TLapeGlobalVar>.Create;
> 
>   for i := 0 to m.Params.Count - 1 do
>     VarStack2 := VarStack2 + getVar(m.Params[i].VarType, VarToStr(Params[i]));
> 
>   if Assigned(m.Res) then
>     VarStack2 := VarStack2 + getVar(m.Res, Result);
> 
> //lpinterpreter.pas
>   RunCode(PPCode, CodeLen, VarStack2, PCodePos(LapeCompiler[ProcName].Ptr)^);
> 
>   ParamVars.Free;
> 
>   if not ExecEvMethodError.IsEmpty and ValidObject(CharObj) then
>     Script_AddToSystemJournal(ExecEvMethodError);
> end;
> ```
> 
> maybe will be useful for you.

Hi, I'm trying to adapt this code for my project. I can call the routine with no param, a routine with params, but it crash when I call a routine with a return result. Can you please advise?
