### ISSUE TITLE
Inline Variable Declaration

### ISSUE THREAD

**Issue by thecocce** [nielsAD/lape#199]
Hi, is there the possibility to implement the "Inline Variable Declaration" lilke recent Delphi compiler?

https://docwiki.embarcadero.com/RADStudio/Sydney/en/Inline_Variable_Declaration

Thanks.

**Comment by ollydev** [comment]
I believe `{$extendedsyntax on}` supports that

**Comment by ollydev** [comment]
Example here:
https://github.com/nielsAD/lape/blob/a02690f1b8992d4c5be326a5292a373bc83f63e8/tests/Algorithms/Death-Star.lap#L23

**Comment by thecocce** [comment]
Ty....
