### ISSUE TITLE
Fails to build `lape.lpi` on trunk FPC with error “lpparser.pas(154,100) Error: Internal error 20231102”

### ISSUE THREAD

**Issue by Alligator-1** [nielsAD/lape#206]
![изображение](https://github.com/user-attachments/assets/35850ceb-0553-4f6c-9bfa-6f04ca5ffcc4)

**Comment by ollydev** [comment]
Yeah it's very broken. I did make a comment on gitlab of what causes it but never got a reply.
I would be amazed if such a change doesn't affect many large projects.
https://gitlab.com/freepascal.org/fpc/source/-/merge_requests/594#note_1981180672

**Comment by Alligator-1** [comment]
If you comment out the `{lpmessages,}` unit here, the compilation succeeds
In general, maybe remove all `lape` units from `*.lpr` ?

https://github.com/nielsAD/lape/blob/522dcefef83f8d48f73d8546adcd19d97ab0bb45/lape.lpr#L14

**Comment by ollydev** [comment]
Done, cannot test though as trunk laz/fpc wont build and i'm too lazy to patch it.

**Comment by Alligator-1** [comment]
Checked - compiled successfully 👍, closing
