### ISSUE TITLE
bug with boolean 

### ISSUE THREAD

**Issue by serjone123** [nielsAD/lape#207]
Hello.
I found some bug with boolean params of procedures in script.

Add procedure to  sample project:
```pascal
procedure GetBool(const Params: PParamArray); {$IFDEF Lape_CDECL}cdecl;{$ENDIF}
begin
  with TForm1(Params^[0]) do
    OutputMemo.Lines.Add(PBool(Params^[1])^.ToString);
end;
```
Then register it in compiler:
```pascal
Compiler.addGlobalMethod('procedure GetBool(b:boolean); ', @GetBool, Self);
```

and finally run this script: 

```pascal
procedure w;
begin
  sleep(2);
end;

begin
  w; //comment this line and will see how follow "false" changed to true 
   // sleep(2);

  GetBool(false);
  GetBool(true);
end.

```

there is result of script: 
```
Compiling Time: 78ms.
-1
-1
Running Time: 0ms.
```

**Comment by slackydev** [comment]
I am confused, if the method is defined as:

> `procedure GetBool(b:boolean);`

Then there is only one argument (one parameter). That parameter is accessed as `Params^[0]`, which is a pointer to a boolean.

So now why do you in the internal method use `Param^[0]^` as a TForm1? There are no other arguments passed, so arg 0 must be the boolean, not argument 1 as in your code `PBool(Params^[1])^.ToString`. There is no argument 1

**Comment by serjone123** [comment]
I am use it because there is using in [sample project](https://github.com/nielsAD/lape/blob/522dcefef83f8d48f73d8546adcd19d97ab0bb45/delphi/main.pas?plain=1#L28) 

```
procedure _Write(const Params: PParamArray); {$IFDEF Lape_CDECL}cdecl;{$ENDIF}
begin
  with TForm1(Params^[0]) do
    OutputMemo.Text := OutputMemo.Text + PlpString(Params^[1])^;
end;
```

And if I use PBool(Params^[0])^, I always got true

**Comment by serjone123** [comment]
I am use it because there is using in [sample project](https://github.com/nielsAD/lape/blob/522dcefef83f8d48f73d8546adcd19d97ab0bb45/delphi/main.pas?plain=1#L28)

procedure _Write(const Params: PParamArray); {$IFDEF Lape_CDECL}cdecl;{$ENDIF}
begin
  with TForm1(Params^[0]) do
    OutputMemo.Text := OutputMemo.Text + PlpString(Params^[1])^;
end;

And if I use PBool(Params^[0])^, I always got true

**Comment by slackydev** [comment]
Yeah, okay, I see, self is passed in this case when using `addGlobalMethod`. It's a bit weird. My bad.

I assume PBool is the same size as Boolean in lape (1 byte)? I can no longer remember, but you can try "ByteBool" to be sure.

(ByteBool(Params^[1]^).ToString

**Comment by serjone123** [comment]
Seems it very different types. There is 00 byte in memory for false and 01 for true. 
So for got right boolean this code work:
```pascal
    b:= Byte(Params^[1]^)  ;
    case b of
      00: booli:= false;
      01: booli:= true;
    end;
    Form1.OutputMemo.Lines.Add(booli.ToString);
```
I think it works some cherezdzhopno. Why not add any helper to lape for getting parameters with0ut pointers? 

That is how i do it in my project (boolean not fixed yet). It is very useful.
![изображение](https://github.com/user-attachments/assets/0096330b-85c5-4dfc-b974-18f2e605bd00)

**Comment by slackydev** [comment]
A True boolean is anything that is not 0. It can be 123, 255, 1, 9.. etc. Types just have to match. If "PBool" is for example a pointer of LongBool which is 4 bytes, but the parameter specifies lape's Boolean which is 1 byte, when we deref the PBool we read outside the bounds of the type (read 4 bytes rather than 1), resulting in nonesensical data. Not sure what type PBool is a pointer to.

So saying a true bool is 01, is slightly incorrect. That is True, but many other values can also be True, what we know is that `0` is false, everything else is True.
