### ISSUE TITLE
Small issue with enums

### ISSUE THREAD

**Issue by WarPie** [nielsAD/lape#37]
Well this is really a tiny not important issue, which is why I haven't reported it before now..

Both these test-cases can, and will from time to time cause lape to crash.
```pascal
type E = (ea, eb, ec, ed=9);  //this can crash lape from time to time
begin
  WriteLn(ed); //InvalidEnum(..)
end;
```
```pascal
type E = (ea=1, eb=2, ec=5, ed=9);
var aa:E;
begin
  aa := ed;
  WriteLn(ed); //InvalidEnum(..)
end.
```

There is also lacking error-handling here, allowing this:
```pascal
type E = (ea=7, eb=1, ec, ed)
```
to compile and crash the interpreter.

-----------------
This is tested with the versions of lape that _Simba_ has used up to this date.

**Comment by nielsAD** [comment]
Should be fixed with referenced commit. Thanks for reporting!
