### ISSUE TITLE
Issue with RaiseException(.., ..)

### ISSUE THREAD

**Issue by WarPie** [nielsAD/lape#38]
Calling `RaiseException(Ex: TIFException; Param: string)` will cause the exception to be raised in the delayed code. This has been worked around in the version Simba uses:
https://github.com/SRL/Lape/commit/0be3c85922646616b56fb312fd1a561e91af62e4

`RaiseException(Ex: TIFException; Param: string)` is found here:
https://github.com/nielsAD/lape/blob/master/lputils.pas#L105

-------------
PS: You never got around to implementing the power operator, we have it added at SRL/Lape:
https://github.com/SRL/Lape/commit/f006d9fca6e0292a29c81ca0e961b8de2f6d3012

**Comment by 3FLLC** [comment]
** Apologies doing through this -- no emails have been replied to, want to engage to fix issues in lape **

NeilsAD, hopefully you still check this.

What is the syntax for try/except/finally - for script to interact with JumpException.Obj? So I can try,except, evaluate, Raise, or handle. my email is ozznixon at gmail.

**Comment by nielsAD** [comment]
This is not really an issue, in my opinion, as it's just there for Pascal Script compatibility. Would be better if we would have stack traces.

**Comment by 3FLLC** [comment]
I have implemented a global object "Exception" in which "daLoop" sets information and the script can then interact with it. I have not changed the parser to support "on:exception", etc. Still out of my comfort zone. Along with the stack trace, and ultimately variable typing.
