### ISSUE TITLE
[Suggestion] else clause for for/while loops

### ISSUE THREAD

**Issue by riwu** [nielsAD/lape#49]
The current behaviour is pretty pointless since checking if at least 1 iteration is executed is trivial and rarely done.
Perhaps add an option (or just change it)  to match its behaviour to that of Python: else clause will be executed if no 'break' happened in the body.

This is in practice much more frequently done, like
```
for 1 to 10 do
begin
  if trySth() then
   break;
end else
begin
  writeln('tried 10 times but still failed!');
  TerminateScript();
end;
```
Without this else clause behaviour, extra variable would be needed to accommodate the control flow.

**Comment by WarPie** [comment]
I really disagree with pythons `for..else`, as calling what python does for "else" is quite inaccurate.
`for`s `else`-statement (in lape) is at least equivalent to that of `if..else`: 
> Did the condition (`for <cond> do`) go through? 
---> Yep .. Do whatever
---> Nope .. Handle it differently, raise an error, whatever..
Which makes more sense than what python does if you ask me.

**Comment by riwu** [comment]
if you think of 'while (condition) do' as repeatedly doing 'if (condition) then' (which is indeed what it does), then the python implementation would make sense (when condition finally turns false, else gets executed; if a break happens in the body, exit the entire block).

It's arguable which one is more intuitive, but pragmatically I have never used the current else construct, whereas the python way is quite frequently encountered. (which is probably why python adopted it in the first place)

**Comment by nielsAD** [comment]
I find this a difficult issue as there's something to say for both behaviours. The current behaviour stems from (HTML) template languages where you either show a list (and iterate through it), or show a default message. To be honest, I didn't know that Python had this until now. It's not _that_ different from how Lape does it, in my opinion, so a transition could be possible.

I do think, however, that it would not be very "Pascalesque", so let's stick with the current behaviour for now. Thanks for the suggestion, though!
