### ISSUE TITLE
keyword in, enum in set - does not work

### ISSUE THREAD

**Issue by 3FLLC** [nielsAD/lape#51]
program setColors;
type
color = (red, blue, yellow, green, white, black, orange);
colors = set of color;

procedure displayColors(c : colors);
const
   names : array [color] of String[7]  = ['red', 'blue', 'yellow', 'green', 'white', 'black', 'orange'];
var
   cl : color;
   s : String;
begin
   s:= ' ';
if red in c then writeln('RED');
   for cl:=red to orange do
if cl=red then writeln('*RED');
      if cl in c then begin // has a bug!
writeln('never gets here');
         if (s<>' ') then s :=s +' , ';
         s:=s+names[cl];
      end;
   writeln('[',s,']');
end;

var
   c : colors;

begin
   c:= [red, blue, yellow, green, white, black, orange];
   displayColors(c);
   c:=[red, blue]+[yellow, green];
   displayColors(c);
   c:=[red, blue, yellow, green, white, black, orange] - [green, white];
   displayColors(c);
   c:= [red, blue, yellow, green, white, black, orange]*[green, white];
   displayColors(c);
end.

**Comment by riwu** [comment]
This is same as Issue #50
In lape, after every iteration the loop variable gets incremented, then checked against the end condition, so after the last iteration 'cl' becomes red+1 (in the other case, A overflows to 0); you should not continue to read from the loop variable after the for loop.

**Comment by nielsAD** [comment]
I think you might be missing a `begin`/`end around the things that should be looped. If I adjust that, it works fine for me. I did fix a compilation bug related to shortstrings (20de939e60c168421f42889d84620f7cb5f171fd).

I'll close this for now. If you think it should be reopened, please let me know. Thanks for reporting!

**Comment by 3FLLC** [comment]
Actually after synchronizing all of my fixes and your fixes, the code works but new issue, setting array[colors] of string[7] will not compile, changing to string, compiles and runs perfectly....

program setColors;

type
 color = (red, blue, yellow, green, white, black, orange);
 colors = set of color;

const
 names : array [color] of String = ['red', 'blue', 'yellow', 'green', 'white', 'black', 'orange'];
// names : array [color] of String[7] = ['red', 'blue', 'yellow', 'green', 'white', 'black', 'orange']; {string[7] now raises "Access Violation"}

procedure displayColors(c : colors);
var
 cl : color;
 s : String;

begin
 s:='';
 for cl:=red to orange do // is not same as issue #50, works!
  if cl in c then begin // has a bug!
   if (s!='') then s+=', ';
   s+=names[cl];
  end;
 writeln('[',s,']');
end;

var
 c : colors;

begin
 displayColors([red]);
 c:= [red, blue, yellow, green, white, black, orange];
 displayColors(c);
end;

**Comment by nielsAD** [comment]
I also ran into that bug running your example program. However, I thought I fixed it with a recent commit (20de939e60c168421f42889d84620f7cb5f171fd), could you confirm you also merged that one in?

**Comment by 3FLLC** [comment]
@nielsAD CONFIRMED works.

Do we support "for in" and range(anytype) that returns low and high of anytype/
// documenting how to migrate from PYTHON...
