### ISSUE TITLE
cloning a variable using @ does not work...

### ISSUE THREAD

**Issue by 3FLLC** [nielsAD/lape#52]
program cloning;

var
   T1:String;
   T2:String;

Begin
   T1:='Hello World!';
   @T2:=@T1;
   Writeln(1,T2);
   T1[1]:='@';
   Writeln(2,T1);
   Writeln(3,T2);
End.

**Comment by riwu** [comment]
@T2 means the address of T2, doesnt make sense to be able to alter the address of a variable.
Try this:
```
var
T1:String;
T2:Pointer;

Begin
T1:='Hello World!';
T2:=@T1;
Writeln(1,T2^);
T1[1]:='@';
Writeln(2,T1);
Writeln(3,T2^);
End.
```

**Comment by nielsAD** [comment]
Yes, as @riwu, this is as designed. This will also fail in Delphi/FPC :)
