### ISSUE TITLE
[Suggestion] Allow nested routine to access param & local var

### ISSUE THREAD

**Issue by riwu** [nielsAD/lape#62]
```
procedure foo(x: integer = 111);
var
  y: Integer = 333;

  procedure nested;
  begin
    writeln(x, ' ', y);
    y := y + 1;
  end;

begin
  nested;
  x:= 999;
  nested;
end; 
```
This is valid in FPC. (prints 111 333, 999 334)
Will be convenient to have it in lape (currently we have to pass them by reference to the nested routine)

**Comment by nielsAD** [comment]
Yes, this would be nice. Can probably be done with implicitly passed variables, similar as to how `inherited` is currentely implemented.

**Comment by nielsAD** [comment]
By default, all parameters/variables will be inherited. If you want to prevent this and get the old behaviour; you can mark the method as `static`.

Thanks for reporting!
