### ISSUE TITLE
Integer value to boolean param

### ISSUE THREAD

**Issue by riwu** [nielsAD/lape#63]
Not sure if it's already fixed:
```
procedure a(x: Boolean);
begin
end;

begin
  a(2); //works even though integer != boolean (doesnt work in fpc)
end.
```
Similar to https://villavu.com/forum/showthread.php?t=110843

**Comment by WarPie** [comment]
In the version of lape you are testing, booleans are integers pretty much to the core.
This behavior has been changed with our boolean fixes, where booleans must have their own evaluation methods. I do however think this is a _feature_ we can consider supporting again, as it's kinda nice to have such a cast implied.

Currently this is the result of assigning bool to int, and vice versa:
* `Can't assign "Int32" to "(False=0, True=1)"`
* `Can't assign "(False=0, True=1)" to "Int32"`

**Comment by riwu** [comment]
Yeah i agree that boolean operators having higher precedence than comparison operators is weird, but probably because in fpc bitwise operators (which usually has higher precedence than comparison) share the same syntax as boolean operators, so it might not be a good idea to deviate from FPC.
 
Converting integer to boolean is trivial (someInt <> 0) and more readable/flexible so i don't think that's necessary at all, esp since like you mentioned, it causes hard-to-debug (for ppl not aware of the abnormal precedence) bugs.

**Comment by riwu** [comment]
```
type
  enum = (a, b, c);

procedure f(x: enum);
begin
end;

begin
  f(1);
end.
```
Should not allow int to be passed to enum params too. If someone does that, he's likely to have made a mistake. Stricter param type check (like in FPC) will prevent many flawed codes and allows greater flexibility in method overloading.

**Comment by WarPie** [comment]
I have never seen that being an issue. And I do like the implicit cast, I feel it often keeps my code cleaner. So my final is that I'd leave it as it is. Not my call tho.

**Comment by riwu** [comment]
Why use an integer argument if the parameter is an enum?
Any example of how it keeps the code cleaner?

**Comment by WarPie** [comment]
You are only looking at one aspect of it, a change like this would affect other things as well, as we would redefine what enum is compatible with:
> `Arr[ltMethod] := someValue;`
> `Arr[Ord(ltMethod)] := someValue;`

**Comment by riwu** [comment]
self.GetCurrentTab()/ltMethod should not return an enum if it's meant to be use as array index? Why not just return integer instead?

Also i think codes should not rely on the ordering of enum. 
One of the main benefits of using enum rather than const is that you can change the ordering/add new const without breaking the code. 
Enum params are generally handled with a case statement.

**Comment by nielsAD** [comment]
I agree. These checks could be a bit more strict. The array index operation should not be in danger as that works with all ordinal types (and does not use cast to integer).
