### ISSUE TITLE
Casting static array to dynamic array

### ISSUE THREAD

**Issue by WarPie** [nielsAD/lape#67]
When you cast a static array where the contents total size is equal to `SizeOf(NativeInt)` into a dynamic array the outcome is not what we expect (it's length is 0), and in the case of casting an open array it will segfault.

**Example (_Length is 0_):**
```pascal
type TIntArray = Array of NativeInt;
var
  static_arr: Array [0..0] of NativeInt;
var
  arr:TIntArray;
begin
  arr := TIntArray(static_arr);
  WriteLn(Length(arr));         //is 0
end;
```

----
**Example (_"segfault"_):**
```pascal
type TIntArray = Array of NativeInt;
var
  Arr: TIntArray;
begin
  Arr := TIntArray([1]);       //Will segfault
end.
```

----
**Example (_other_):**
> http://pastebin.com/2R9Kvu0i

**Comment by nielsAD** [comment]
Thanks for reporting!
