### ISSUE TITLE
ToString missing type

### ISSUE THREAD

**Issue by 3FLLC** [nielsAD/lape#72]
Tried to run this:
procedure Task;
var
  x: Set Of Byte;
begin
  x:= [2,4,8,16,32,64,256];
  Writeln(x);  
end;

What change do I need to do for ToString to handle X? Tried a couple things, none were the correct solution.

**Comment by nielsAD** [comment]
This snippet seems to work for me (1fb908a3b055f57f352c8643015b1ed13bb3f44b might be related?).  Please let me know if you experienced this on the latest version. For now, I'll close this.
