### ISSUE TITLE
Memory Leak(s)

### ISSUE THREAD

**Issue by 3FLLC** [nielsAD/lape#84]
I found many memory leaks, too many to release my product. So, I have pulled the latest code, and as I reproduce them, I will share them. Here is my simple LAPE CLI code:

    {$mode delphi}{$H+}
    
    uses
       SysUtils,
       dxutil_environment,
       lpparser,
       lpcompiler,
       lpvartypes,
       lpeval,
       lpinterpreter;
    
    Var
       T:Comp;
       Parser: TLapeTokenizerBase;
       Compiler: TLapeCompiler;
    
    begin
       Parser := nil;
       Compiler := nil;
    try
       Parser := TLapeTokenizerFile.Create(Paramstr(Paramcount));
       Compiler := TLapeCompiler.Create(Parser);
      
      try
        t := TimeCounter;
        if Compiler.Compile() then
          System.Writeln('Compiling Time: ' ,TimeCounterDiff(t,TimeCounter), 'ms.')
        else
          System.Writeln('Error!');
      except
        on E: Exception do
        begin
          System.Writeln('Compilation error: "' + E.Message + '"');
          Exit;
        end;
      end;

      try
          t := TimeCounter;
          System.Writeln(LineEnding);
          RunCode(Compiler.Emitter.Code);
          System.Writeln('Running Time: ' ,TimeCounterDiff(t,TimeCounter), 'ms.');
      except
        on E: Exception do
          System.Writeln(E.Message);
      end;
    finally
      if (Compiler <> nil) then Compiler.Free()
      else if (Parser <> nil) then Parser.Free();
    end;
    end.

// TimeCounter is linked to getTickCount64 on Windows, and Time Spec on Linux. This is basically your main.pp w/o FFI stuff.

Compile option:
fpc test -Fu/source/bpdx/ -gl -gh -O- -Si

FPC Version:
Free Pascal Compiler version 2.6.4+dfsg-8 [2015/08/14] for x86_64

Commandline:
/test tests/Arithmetics_Boolean.lap

Output:
Compiling Time: 12ms.

Boolean  :: Passed
ByteBool :: Passed
WordBool :: Passed
LongBool :: Passed
Running Time: 0ms.
Heap dump by heaptrc unit
62472 memory blocks allocated : 5642730/5858176
62471 memory blocks freed     : 5642684/5858128
1 unfreed memory blocks : 46
True heap size : 950272
True free heap : 950080
Should be : 950096
Call trace for block $00007FF8EF5AEE80 size 46
  $00000000004007E0 line 21 of test.pp
  $000000000040062D

Line #21 is: Parser := TLapeTokenizerFile.Create(Paramstr(Paramcount));

**Comment by 3FLLC** [comment]
I tried changing TStringList logic to Binary File I/O - still same result. I have compiled with -gl -gh - and did a rebuild, just so I could see if it was further deep in the code, no luck. I enabled your Object Track - showed everything being freed. I even tried compiler(parser, false) and manually free praser obj - get same result.

**Comment by nielsAD** [comment]
I'm aware of this issue. It's related to (not) storing the filenames in the bytecode. It should disappear when compiling with `Lape_EmitPos` defined. [lpcodeemitter.pas#L459](https://github.com/nielsAD/lape/blob/master/lpcodeemitter.pas#L459) is the offending line. Should be fixed by either storing file indices or guaranteeing proper reference counter on class destruction.
Thanks for reporting!

**Comment by 3FLLC** [comment]
More attempts. create a file called nada.lap

     begin
     end.

run, no memory leak.

Create funcs.lap and procs.lap - with one or more functions/procedures each file.

Compiling Time: 5ms.


Running Time: 0ms.
Heap dump by heaptrc unit
55711 memory blocks allocated : 4012997/4206808
55710 memory blocks freed     : 4012973/4206784
1 unfreed memory blocks : 24
True heap size : 819200
True free heap : 819008
Should be : 819048
Call trace for block $00007FBC3362AE80 size 24
  $0000000000400A7C line 40 of test.pp // line changed because of debug messages in my CLI
  $00000000004008AD

So as soon as I define a function or procedure, there is a 24 byte leak. Adding parameters does not change this, and adding global variables does not change this. However, for some reason running: tests/Arithmetics_Float.lap leaks 44 bytes, while tests/Arithmetics_Integer.lap leaks 46 bytes.

Still researching why those are different, and why just adding 1 function or procedure produces a leak.

Ozz

**Comment by 3FLLC** [comment]
Just saw your comment. Yes, is I remove that directive - 0 leaks! AWESOME! Now I am going to continue merging your latest LAPE into Modern Pascal, and see if I can produce a Game Server with Zero leaks again! (will also try to figure a way to fix that leak as I go)... will share all that I can in my FORK! (like ifdef, ifopt, etc. many *little contributions*). ;-)

PS. How/When/Why would one use ExposeGlobals and TransverseGlobals? (my original LAPE zip did not have lputils in it).
