### ISSUE TITLE
Problem with Pointer/Object/Instances

### ISSUE THREAD

**Issue by 3FLLC** [nielsAD/lape#92]
@nielsAD 32bit "Access Violation" - 64bit works perfectly

      with Compiler do begin
        addClass('TDXSock', 'Pointer');
        addGlobalProcedure('TDXSock.Init', @TDXSock_Init);
        addGlobalFunction('TDXSock.ConnectTo(Const Host:String;Const Port:Word):Boolean', @TDXSock_Connect);
    ...etc...

this fails in 32bit:

     //constructor Create();
     procedure TDXSock_Init(const Params: PParamArray); cdecl;
     begin
       PDXSock(Params^[0])^ := TDXSock.Create();
    end;

If I change to, it doesn't fail -- but next routine fails...

     //constructor Create();
     procedure TDXSock_Init(const Params: PParamArray); cdecl;
     begin
       TDXSock(Params^[0]) := TDXSock.Create();
     end;
     
     //function Connect(Const Host:String;Const Port:Word):Boolean;
     procedure TDXSock_Connect(const Params: PParamArray; const Result: Pointer);
     begin
        PBoolean(Result)^ := PDXSock(Params^[0])^.Connect(PlpString(Params^[1])^,PWord(Params^[2])^);
     end;

or if I change PDXSock(params^[0])^ to TDXSock(params^[0]).Connect .. .it still raises Access Violation. My environment limits me from using fp or gdm to trace .. so I come to you for help. It appears that in 64bit binaries all of my objects work perfectly. Recompile same code on 32bit any OS, and run - LA-PE AV's on *any* object that is defined in the host code. I assumed LongWord vs LongInt for pointers - but, do not see that when tracing by hand. It literally AV's on either Params^[0] := instance, or type cast Params^[0] to class.

**Comment by nielsAD** [comment]
From your code fragment it seems you're declaring one function with `cdecl` and the other without. Are you compiling with `$Lape_CDECL`? Make sure the function declarations are consistent with this setting.

**Comment by 3FLLC** [comment]
WOW! removed cdecl in the few places I still had it - and viola - 32bit works!! Thank you! Now, could you explain (if you know), why having cdecl breaks things in 32bit?

**Comment by nielsAD** [comment]
It changes the calling convention, i.e. the way arguments are passed to the function (via stack / registers, left to right / right to left). On `x64`, the calling convention modifiers (such as `cdecl`) are ignored and the platform default is used.
