### ISSUE TITLE
New Hints Feature, has bug...

### ISSUE THREAD

**Issue by 3FLLC** [nielsAD/lape#95]
```
begin
   for var loop:=1 to 1000000 do MakeMask(7);
end.
```

New HINT from Olly, returns: Variable "loop" not used at line 2, column 20 in file "testhints.p"

**Comment by Olly-** [comment]
Script sided you don't actually use the variable, but I do see where you're coming from since it's used internally. 

Are you aware you can do the following:
```
for 0 to 1000000 do MakeMask(7);
```

**Comment by nielsAD** [comment]
I think this is desired behavior. As @Olly- noted, you don't *have* to define a variable there.

**Comment by 3FLLC** [comment]
Okay, I will track it down and fix it - I know I can define the var globally, however, when inline, it should not hint.
