### ISSUE TITLE
ToString - not working on sets.

### ISSUE THREAD

**Issue by 3FLLC** [nielsAD/lape#97]
program HelloSetWorld;
    uses display;
    
    type
       Days=(Sun=0, Mon, Tue, Wed, Thr, Fri, Sat);
       DaysWorked=Set of Days;
    
    var
       Schedule:DaysWorked;
    
    begin
       Schedule:=[Mon, Wed, Thr, Fri];
       Writeln('This week I work 9-5 on ',Schedule);
       Schedule+=[Tue];
       Schedule-=[Thr];
       Writeln('Next week I work 9-5 on ',Schedule);
       ReadKey;
    end.

returns:

    Compilation error: "Type expected at line 2, column 82 in file "!addGlobalFuncBdy::ToString""

Not sure how to fix this... anyone know where/what to change?
Ozz

**Comment by Olly-** [comment]
This works on the latest lape:
```
This week I work 9-5 on [Mon, Wed, Thr, Fri]
Next week I work 9-5 on [Mon, Tue, Wed, Fri]
```

It's something you've changed.

**Comment by WarPie** [comment]
You have pulled this issue up twice now already, where we have one after another said that it works..
https://github.com/nielsAD/lape/issues/78
https://github.com/nielsAD/lape/issues/72

**Comment by 3FLLC** [comment]
* Thanks guys! But, I am getting this in my LAPE engine too. So I am missing a patch, I will go back through and synchronize again. I thought this worked, as it is in my "working examples" folder. May be the default $ options. I am trying to avoid changing any core code, and just abstracting/overriding my changes. I do not like reporting things as bugs, but, I am unaware of any other way of asking... is there?

**Comment by nielsAD** [comment]
As @WarPie and @Olly- have mentioned, this works as expected. I refer to a commit in #72, make sure you have that merged.

**Comment by 3FLLC** [comment]
I verified I have all the patches, I dump the DelayedCode - everything is there - yet, I still get this error... so I will keep digging around, and when I find what else can cause this, I will share - thanks!

**Comment by 3FLLC** [comment]
[Solution/Cause]: Change the core to support namespaces - I disabled support for System.String - which is what this error was sharing (unknown System.String in the ToString routine). Changed to String and all works.
